name: deploy
on: workflow_dispatch
jobs:
  hit-deploy-hook:
    runs-on: ubuntu-latest
    steps:
      - name: Hit deploy hook
        env:
          cf_deploy_hook: ${{ secrets.CF_DEPLOY_HOOK }}
        run: |
          curl -X POST "$cf_deploy_hook"
